#%RAML 1.0
version: 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/b835c3bb-a8ae-4ec9-bcbd-2b79e4ccc125/ # 
title: CaptstoneProjectMgmt
types:
  users:
    type: object
    properties:
     first: 
      required: true
     type: string
     last:
      required: true
      type: string
     Department:
      required: true
      type: string
     id:
      required: true
      type: integer
/Users:
  get:
    description: provides all users information
    responses:
      200:
        body:
          application/json:
            example:  !include examples/exampleGetUser.Json
  post:
    description: provide all users information
    responses:
      200:
        body:
          application/json:
            example: !include examples/examplePost.Json
                   
  /{ID}:
    get:
      description: API is used to search a particular user
      responses:
        200:
          body:
            application/json:
              example: !include examples/exampleGetUser.Json
    put:
      description: API is used to update users information
      responses:
        200:
          body:
            application/json:
              example: !include examples/examplePut.Json 
    delete:
      description: API is used to delete a particular user
      responses:
        200:
          body:
            application/json:
              example: !include examples/exampleDelete.json 
      
